#!/usr/bin/env bash
# Script: 11-manage_my_process
# Description: Bash (init) script to manage the manage_my_process script.

PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="./manage_my_process"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running."
        return 1
    fi

    "$PROCESS_SCRIPT" &
    echo $! > "$PID_FILE"
    echo "manage_my_process started."
}

stop() {
    if [ ! -f "$PID_FILE" ]; then
        echo "manage_my_process is not running."
        return 1
    fi

    pid=$(cat "$PID_FILE")
    kill $pid
    rm "$PID_FILE"
    echo "manage_my_process stopped."
}

restart() {
    stop
    start
    echo "manage_my_process restarted."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
